name: Ruby

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, truffleruby, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby -e 'sentence = "This is a sample sentence."; puts sentence.gsub(/a/, "")'
    - run: ruby -e 'sentence = "Th1s 1s a sampl3 s3nt3nc3."; puts sentence.gsub(/[0123456789]/, "!"); puts sentence.gsub(/[0-9]/, "!")' 
