name: Ruby

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, truffleruby, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: sudo apt-get update
    - run: sudo apt-get install libsqlite3-dev libxml2-dev libxslt-dev
    - run: gem install rails
    - run: rails new cucumber_bdd_how_to
    - run: cat Gemfile
      working-directory: ./cucumber_bdd_how_to
    - run: mv Gemfile.example cucumber_bdd_how_to/Gemfile
    - run: bundler install
      working-directory: ./cucumber_bdd_how_to
    - run: rails generate cucumber:install
      working-directory: ./cucumber_bdd_how_to
    - run: mv hello_world.feature cucumber_bdd_how_to/features
    - run: bundle exec cucumber features/hello_world.feature
      working-directory: ./cucumber_bdd_how_to
