name: Ruby

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, truffleruby, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby test_gsub.rb 
    - run: sudo apt-get install libsqlite3-dev libxml2-dev libxslt-dev
    - run: gem install selenium-webdriver -v 3.142.7
    - run: gem install webdrivers -v 4.2.0
    - run: gem install capybara -v 3.31.0
    - run: gem install cucumber-rails -v 2.0.0
    - run: ruby capabilities.rb
